wandb_version: 1

model name:
  desc: null
  value: builtins.type
run name:
  desc: null
  value: Simplest/testrun
epochs:
  desc: null
  value: 1
learning rate:
  desc: null
  value: 0.0003
optimizer:
  desc: null
  value: AdamW
uses scheduler:
  desc: null
  value: false
base_lr:
  desc: null
  value: 0.0001
max_lr:
  desc: null
  value: 0.001
lr_steps:
  desc: null
  value: 9
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1710108706.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.4
      8:
      - 1
      - 2
      - 5
      13: linux-x86_64
